/*
 * This source file was generated by the Gradle 'init' task
 */
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
}
